let number1 = 25;
let number2 = 12;
let sum = number1 + number2;
let poruka = "Suma je " + sum;
console.log(poruka);
let razlika = number1 - number2;
poruka = "Razlika je " + razlika;
console.log(poruka);
let proizvod = number1 * number2;
poruka = "Proizvod je " + proizvod;
console.log(poruka);
let division = number1 / number2;
poruka = "Rezultat je " + division;
console.log(poruka);
let error = number1 % number2;
poruka = "Rezultat je " + error;
console.log(poruka);